-- СЕВЕРНАЯ ЗВЕЗДА — FINAL DIAMOND
-- Запустить ОДИН РАЗ через Supabase -> SQL Editor -> New query -> Run.
-- Скрипт идемпотентный: повторный запуск безопасен.

create extension if not exists pgcrypto;

-- Поля V5/V6
alter table public.bookings add column if not exists admin_note text;
alter table public.bookings add column if not exists public_token text;
alter table public.bookings add column if not exists checked_in_at timestamptz;
alter table public.bookings add column if not exists started_at timestamptz;
alter table public.bookings add column if not exists completed_at timestamptz;
alter table public.bookings add column if not exists updated_at timestamptz not null default now();
alter table public.bookings add column if not exists phone_norm text;
alter table public.bookings add column if not exists request_id text;
alter table public.bookings add column if not exists client_notice text;
alter table public.bookings add column if not exists client_notice_at timestamptz;
alter table public.bookings add column if not exists previous_booking_date date;
alter table public.bookings add column if not exists previous_booking_time time;

update public.bookings set phone_norm=regexp_replace(coalesce(phone,''),'\D','','g') where phone_norm is null or phone_norm='';
update public.bookings set public_token=encode(gen_random_bytes(24),'hex') where public_token is null or public_token='';
alter table public.bookings alter column public_token set default encode(gen_random_bytes(24),'hex');
alter table public.bookings alter column public_token set not null;

create unique index if not exists bookings_public_token_unique on public.bookings(public_token);
create unique index if not exists bookings_request_id_unique on public.bookings(request_id) where request_id is not null;
create index if not exists bookings_phone_norm_created_idx on public.bookings(phone_norm,created_at desc);

-- Статусы
alter table public.bookings drop constraint if exists bookings_status_check;
alter table public.bookings add constraint bookings_status_check check(status in ('new','accepted','arrived','in_progress','completed','rejected','no_show','cancelled'));

-- Один активный пациент на один слот. Отменённые/отклонённые слот освобождают.
drop index if exists bookings_date_time_type_unique;
drop index if exists bookings_date_time_unique;
create unique index bookings_date_time_unique on public.bookings(booking_date,booking_time)
where service <> 'inpatient' and status not in ('rejected','cancelled');

-- Отзывы полностью удалены из продукта.
drop table if exists public.reviews cascade;

-- Услуги и цены
create table if not exists public.clinic_services(
  service_key text primary key,
  name text not null,
  icon text not null default '🐾',
  price_label text not null default '',
  description text not null default '',
  prep text not null default '',
  sort_order integer not null default 100,
  enabled boolean not null default true,
  updated_at timestamptz not null default now()
);

-- Push
create table if not exists public.push_subscriptions(
  id bigint generated by default as identity primary key,
  endpoint text not null,
  subscription jsonb not null,
  created_at timestamptz not null default now()
);
delete from public.push_subscriptions a using public.push_subscriptions b where a.ctid<b.ctid and a.endpoint=b.endpoint;
create unique index if not exists push_subscriptions_endpoint_unique on public.push_subscriptions(endpoint);

-- Атомарный rate-limit. Храним только HMAC-хэш, исходный IP/номер сюда не попадает.
create table if not exists public.rate_limit_events(
  id bigint generated by default as identity primary key,
  scope text not null,
  key_hash text not null,
  created_at timestamptz not null default now()
);
create index if not exists rate_limit_lookup_idx on public.rate_limit_events(scope,key_hash,created_at desc);
create index if not exists rate_limit_created_idx on public.rate_limit_events(created_at);

create or replace function public.consume_public_rate_limit(p_scope text,p_key_hash text,p_limit integer,p_window_seconds integer)
returns boolean language plpgsql security definer set search_path=public as $$
declare v_count integer; v_window integer;
begin
  v_window:=greatest(10,least(coalesce(p_window_seconds,60),86400));
  perform pg_advisory_xact_lock(hashtextextended(coalesce(p_scope,'')||':'||coalesce(p_key_hash,''),0));
  delete from public.rate_limit_events where created_at<now()-interval '2 days';
  delete from public.rate_limit_events where scope=p_scope and key_hash=p_key_hash and created_at<now()-make_interval(secs=>v_window);
  select count(*) into v_count from public.rate_limit_events where scope=p_scope and key_hash=p_key_hash and created_at>=now()-make_interval(secs=>v_window);
  if v_count>=greatest(1,least(coalesce(p_limit,1),100)) then return false; end if;
  insert into public.rate_limit_events(scope,key_hash) values(p_scope,p_key_hash);
  return true;
end $$;
revoke all on function public.consume_public_rate_limit(text,text,integer,integer) from public,anon,authenticated;
grant execute on function public.consume_public_rate_limit(text,text,integer,integer) to service_role;

-- Последний рубеж: даже если кто-то обойдёт интерфейс сайта, БД не примет поток одинаковых публичных заявок.
create or replace function public.guard_public_booking_insert()
returns trigger language plpgsql set search_path=public as $$
declare v_recent integer;
begin
  -- Администратор создаёт записи без request_id и под этот лимит не попадает.
  if new.request_id is null then return new; end if;
  if coalesce(new.phone_norm,'')='' then raise exception 'BOOKING_RATE_LIMIT'; end if;

  if exists(
    select 1 from public.bookings b
    where b.request_id is not null
      and b.phone_norm=new.phone_norm
      and lower(trim(b.pet))=lower(trim(new.pet))
      and b.service=new.service
      and b.created_at>now()-interval '30 minutes'
      and b.status not in ('rejected','cancelled')
  ) then raise exception 'DUPLICATE_BOOKING'; end if;

  select count(*) into v_recent from public.bookings b
  where b.request_id is not null
    and b.phone_norm=new.phone_norm
    and b.created_at>now()-interval '30 minutes';
  if v_recent>=3 then raise exception 'BOOKING_RATE_LIMIT'; end if;
  return new;
end $$;

drop trigger if exists trg_guard_public_booking_insert on public.bookings;
create trigger trg_guard_public_booking_insert before insert on public.bookings for each row execute function public.guard_public_booking_insert();

-- Закрываем прямой браузерный доступ. Клиент работает только через Netlify Functions.
alter table public.bookings enable row level security;
alter table public.clinic_services enable row level security;
alter table public.push_subscriptions enable row level security;
alter table public.rate_limit_events enable row level security;
